name: Gradle Build
on: {push: {tags: null}}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: vaccovecrana/gitflow-oss-java-slim@testing
        with:
          orgConfig: https://vacco-oss.s3.us-east-2.amazonaws.com/vacco-org-config.json
          secretContext: ${{toJson(secrets)}}
